### PR TITLE
feat: Add basic SSR support and peerDependecies to `react 18.2.0`

### LINKED ISSUE #812: Checkbox fungerer ikke med next.js
### Description of the bug

Checkbox vises ikke som beskrevet i eksemplet.
Når boksen er checket kommer det ett hvitt kryss på hvit bakgrunn, hover effekt fungerer heller ikke

### Steps To Reproduce

1. Opprett ett nytt next prosjekt med `npx create-next-app@latest`
2. Fjern all styling og boilerplate
3. Installer npm pakken med desigsystemet `npm install @digdir/design-system-react`
4. Importer Checkbox eksempel fra https://digdir.github.io/designsystem/?path=/docs/felles-checkbox-group--docs

### Additional Information

Versjoner jeg bruker:
node: 18.12.1
next: 13.4.19
react: 18.2.0

Bilde av feilen:
image

### LINKED ISSUE #860: Add "use client" to dist bundle for react package
Currently our react package crashes when used in combination with React Server Components. 

As a hotfix to prevent crashing we want to add ["use client"](https://react.dev/reference/react/use-client) to our dist bundle to prevent crashes now. 

Better SSR support will be added in the future.

### PR DESCRIPTION
**Pull request by Barsnes**
Resolves #860
Fixes #812 

Makes all components client components, to support SSR.

### CODE REVIEW

**Comment by Barsnes** [comment]
I did a diff check on `dist/cjs/index.js`, and the only difference between the bundles seems to be `"use client"`
image

**Comment by Barsnes** [comment]
I did a diff check on `dist/esm/index.js` as well, and here it seems like there are more changes. See: [https://www.diffchecker.com/WRdSVoPS/](https://www.diffchecker.com/WRdSVoPS/)

I will have to test all the components to make sure they still work as expected.

**Comment by Barsnes** [comment]
We needed to update `typescript` and `@types/react` to their latest versions. If we don't, we will get type errors when using components in Next.

**Comment by Barsnes** [comment]
I have tested with a local build of the latest commit on both a NextJS and CRA app.
Everything works as expected.
We can still use dot notation in CRA, but in Next we need to import each component by itself.
This is because every component is now a client component, meaning we dont have access to anything inside it, before we are on the client.

**Comment by Barsnes** [comment]
This also closes #812 - Screenshot is of a next app using the checkbox on a server component.
image

**Comment by mimarz** [comment]
> This also closes #812 - Screenshot is of a next app using the checkbox on a server component. image

Please link to it in the PR description using the "fixes" [Github keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) so its linked and closed when PR is merged :) You se a slightly dotted line under the keywords when its linked correctly

**Review by mimarz — APPROVED** [review]
LGTM 👍 

Fixed some storefront errors. 

We haven't documented anything about using our compund components on the server side (`CheckboxGroup` instead of `Checkbox.Group`) but lets see how it plays out with updating the rest to be server components

**Pull request merged**
