### PR TITLE
fix(DropDownMenuItem): add list style none

### PR DESCRIPTION
**Pull request by Albertlarsen**
fixes: #1181

### CODE REVIEW

**Comment by mimarz** [comment]
> I'm not sure if we should do this. The user **should** wrap `Item` in a `Group`, otherwise we have `li`s without a `ul` wrapping it. @mimarz thoughts?

Could `DropdownMenu` not also be an `ul`?

**Comment by Albertlarsen** [comment]
I agree with that we should instead say that they need to wrap it in DropDownMenu for semantic purpose but I then I wonder why it is in the Todo-column in the board 😅

**Comment by Barsnes** [comment]
> > I'm not sure if we should do this. The user **should** wrap `Item` in a `Group`, otherwise we have `li`s without a `ul` wrapping it. @mimarz thoughts?
> 
> Could `DropdownMenu` not also be an `ul`?

It could, but we need to do some testing to see if screenreaders break on this. The group currently has `role="group"` 🤔  I think it should be fine, since the whole `DropdownMenu` has a `role="menu"`, and the `Item`s `role="menuitem"`

**Comment by mimarz** [comment]
> Don't know how to fix the the things that's causing the build to fail.

This is due to issue #1124

**Comment by Barsnes** [comment]
> > Don't know how to fix the the things that's causing the build to fail.
> 
> This is due to issue #1124

I think we might have to remove the use of `Box`, unless we can find a better solution to this 🤔 
We could get away by using a more generic type, but I don't think that is an optimal solution

**Comment by mimarz** [comment]
> > > Don't know how to fix the the things that's causing the build to fail.
> > 
> > 
> > This is due to issue #1124
> 
> I think we might have to remove the use of `Box`, unless we can find a better solution to this 🤔 We could get away by using a more generic type, but I don't think that is an optimal solution

Aye, suggest just a `ul` and copy the two line for border and shadow its using from `Box`

**Review by Barsnes — CHANGES_REQUESTED** [review]
We can't have `ul` as a child of `ul`, we need to wrap it in a `li` first, unless we just want to use a `div`

image

```html
<ul>
  <li>Item 1</li>
  <li>
    <ul>
      <li>Child item 1</li>
      <li>Child item 2</li>
    </ul>
  </li>
  <li>Item 3</li>
</ul>

**Review by mimarz — APPROVED** [review]
LGTM

**Comment by Barsnes** [comment]
> ~LGTM~

You can do a review now - just added a li wrapper. It should not need any roles or anything

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Review by Barsnes — APPROVED** [review]
🚀

**Pull request merged**
