### PR TITLE
style: new warning color tokens

### PR DESCRIPTION
**Pull request by mrosvik**

### CODE REVIEW

**Comment by mimarz** [comment]
hmm, didn't look like the deploy preview workflow got triggered here on changes from github actions generating new tokens @Thuneer

**Comment by Thuneer** [comment]
This has to be investigated further. I Suspect that the Token Build action doesn't have the right permissions to be able to trigger the Preview Workflows. I created an [issue](https://github.com/orgs/digdir/projects/3/views/1?filterQuery=-label%3A%22documentation%2Fguidelines%22+-label%3A%22pattern%22+-label%3A%22%F0%9F%A7%AD+roadmap%22++action&pane=issue&itemId=48097146).

**Review by mimarz — APPROVED** [review]
LGTM 👍 

Do we have an issue to update relevant react components with these new tokens? @mrosvik @Febakke

**Comment by Febakke** [comment]
> LGTM 👍
> 
> Do we have an issue to update relevant react components with these new tokens? @mrosvik @Febakke

Related to the tag changes made in Figma: #1261

**Pull request merged**
