### PR TITLE
docs(Storybook): :wrench: Change Storybook information structure

### LINKED ISSUE #743: Storybook: Increase text size and limit line length
Justere paragraf-tekst på Storybook opp til 18px (medium paragraph) og sette en maksbredde på innholdet slik at det ikke blir mer 70 tegn per linje.

> For best mulig lesbarhet for alle brukere, bør det ikke være mer enn 65-70 tegn per linje inkludert mellomrom. Da blir teksten mer innbydende og mindre overveldende, og er særlig viktig for blant annet brukere med lesevansker eller konsentrasjonsvansker. https://www.uutilsynet.no/veiledning/tekst-og-struktur/226

### PR DESCRIPTION
**Pull request by mimarz**
resolves #743

- Using design system components in docs component `Information`. 
- Using our own componets for correct font size. line height etc.
- Could not change the `code` element as it would break the bigger code previews used under "Bruk". Need to find some solution for this. Suggest a separate issue if it becomes a problem.
- Changed status on component overview from beta/stabil to altinn/felles to better reflect changes and work we are doing. 
- Sidebar better reflects major state of components.
- Cleaned up and simplified sidebar structure.

### CODE REVIEW

**Comment by mrosvik** [comment]
Header on Alert looks a bit weird. 
image

**Comment by mimarz** [comment]
> @mimarz Header on Alert looks a bit weird. Could the header be set to size xsmall? Also, I think the spacing between header and paragraph is to large, maybe that will be corrected as well when header is set to xsmall?
> 
> image

I'll try a smaller heading size. Yeah, storybook is applying a lot of its own styles ontop of our components :/

**Comment by mimarz** [comment]
Adjusted Information now, have another look @mrosvik :)

**Comment by mrosvik** [comment]
Looks great! 🙌 The new component structure is also much more clear.

**Pull request merged**
