### PR TITLE
docs: :memo: Updated docs `Chips` doc with development information

### PR DESCRIPTION
**Pull request by mimarz**
- Replaced `TokenBlock` with `Information` for a static important information block to be used in Storybook
- Added `Information` with new "in development" text
- Removed `BetaBlock` from both storefront and docs-components
- Replaced `BetaBlock` usage with `Information text="beta"`

### CODE REVIEW

**Comment by Thuneer** [comment]
Cool!

I have some feedback on the design and spacing to make it look even better (maybe) :)

image

**Information**

```
.container {
  background-color: var(--fds-semantic-surface-warning-subtle);
  border-left: 8px solid var(--fds-semantic-border-warning-default);
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  width: auto;
  margin-top: 24px !important;
  margin-bottom: 2rem !important;
}

.desc > p {
  font: var(--fds-typography-paragraph-short-xsmall) !important;
  margin-top: 8px !important;
  margin-bottom: 0 !important;
  line-height: 1.5em !important;
}

.beta {
  background-color: #f1ecff;
  border-left: 8px solid #6544c5;
}

.title {
  font: var(--fds-typography-heading-xxsmall) !important;
  border-bottom: 0 !important;
  margin-bottom: 0 !important;
  padding-bottom: 0 !important;
}
```

**Beta block**

Could maybe replace the BetaBlock component with this component?

```
.container {
  background-color: #f1ecff;
  border-left: 8px solid #6544c5;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  width: auto;
  margin-top: 24px !important;
  margin-bottom: 2rem !important;
}

.title {
  font: var(--fds-typography-heading-xxsmall) !important;
  margin-bottom: 16px;
  margin-bottom: 8px !important;
}

.desc > * p {
  font: var(--fds-typography-paragraph-short-small) !important;
}
```

**Comment by mimarz** [comment]
> ... 
> **Beta block**
> 
> Could maybe replace the BetaBlock component with this component?
> ...

Jepp! I'll fix it in this PR

**Comment by mimarz** [comment]
Ready for another review @Thuneer

**Review by Thuneer — APPROVED** [review]
Looks good!

**Pull request merged**
