### PR TITLE
feat: Add `htmlSize` to `NativeSelect` and `Textfield`

### LINKED ISSUE #962: Support native `size` attribute in some of our forms components
We are overriding the native [size](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#size) attribute on `Textfield`, ~`Textarea`~ & `NativeSelect` with our own size component size options. 

We should find a way for users to be able to set this as there are use-cases where they might need to do so. 

Maybe make a side-prop for it like Aksel has with `htmlSize`? 🤔

### PR DESCRIPTION
**Pull request by Barsnes**
Resolves #962

### CODE REVIEW

**Comment by mimarz** [comment]
Looking at the name now, would make more sense to call this prop `nativeSize`, would synergize with our naming of `NativeSelect`. What do you think?

**Comment by Barsnes** [comment]
> Looking at the name now, would make more sense to call this prop `nativeSize`, would synergize with our naming of `NativeSelect`. What do you think?

I think `html` makes more sense in this context, since it is an html attribute.
MDN docs also use the name "html attributes" when talking about them, and not "native attributes"

**Review by mimarz — APPROVED** [review]
LGTM 🚀

**Comment by mimarz** [comment]
> > Looking at the name now, would make more sense to call this prop `nativeSize`, would synergize with our naming of `NativeSelect`. What do you think?
> 
> I think `html` makes more sense in this context, since it is an html attribute. MDN docs also use the name "html attributes" when talking about them, and not "native attributes"

Good point!

**Pull request merged**
