### PR TITLE
chore: moved storefront into apps folder

### LINKED ISSUE #971: Move `storefront` to `apps` folder
Since we have more apps now and its easier to consolidate "apps" stuff, lets move `storefront` into apps folder.

Once moved make sure to check atleast following for updating paths.
- Vercel
- Github workflows 
- Search and replace in repository

### PR DESCRIPTION
**Pull request by Thuneer**
Resolves #971 

* Moved folder into apps
* Updated yarn workspaces
* Updated Vercel with the new base path
* Updated github actions with correct path

image

### CODE REVIEW

**Review by Barsnes — COMMENTED** [review]
Looks good, and preview deployment is working 👍🏼
Will previews for older branches still work, or do they all need to be updated once this is merged?

**Comment by Thuneer** [comment]
> Looks good, and preview deployment is working 👍🏼 Will previews for older branches still work, or do they all need to be updated once this is merged?

The latter. At the moment no preview deployments in other branches will work because config in Vercel has changed.

**Comment by Barsnes** [comment]
> > Looks good, and preview deployment is working 👍🏼 Will previews for older branches still work, or do they all need to be updated once this is merged?
> 
> The latter. At the moment no preview deployments in other branches will work because config in Vercel has changed.

Alright, we don't have tons of PRs right now. Can you go trough all affected brances and merge main after you merge this?
You could just do it from github, and ignore branches with merge conflics.

**Comment by Thuneer** [comment]
> > > Looks good, and preview deployment is working 👍🏼 Will previews for older branches still work, or do they all need to be updated once this is merged?
> > 
> > 
> > The latter. At the moment no preview deployments in other branches will work because config in Vercel has changed.
> 
> Alright, we don't have tons of PRs right now. Can you go trough all affected brances and merge main after you merge this? You could just do it from github, and ignore branches with merge conflics.

Will do.

**Review by Barsnes — APPROVED** [review]

**Pull request merged**
