### PR TITLE
style: added color palette for altinn brand

### PR DESCRIPTION
**Pull request by mrosvik**
Resolves https://github.com/digdir/designsystem/issues/305

### CODE REVIEW

**Comment by mimarz** [comment]
Typography for body short is missing. Did you forget to pull from main before branching? 😅

**Comment by mimarz** [comment]
I added the missing typography tokens :)

**Comment by mrosvik** [comment]
Sorry.. 🙈 
And thanks! ❤️

**Review by mimarz — APPROVED** [review]
LGTM 👍

**Pull request merged**
